services:
    victoire_core.widget_disqus.content_resolver:
        class: Victoire\Widget\DisqusBundle\Resolver\WidgetDisqusContentResolver
        parent: victoire_widget.base_widget_content_resolver
        arguments:
            - "%victoire_widget_disqus.disqus_name%"
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Disqus }

    victoire.widget.disqus:
        class: Victoire\Widget\DisqusBundle\Entity\WidgetDisqus

    victoire.widget.form.disqus:
        class: Victoire\Widget\DisqusBundle\Form\WidgetDisqusType
        tags:
            - { name: form.type }
